version: '3.3'
services:
  backend:
    image: ghcr.io/boatprakit/factory-dashboard:main
    ports:
      - 80:3000
    volumes:
      - ~/ssl:/ssl
networks:
  default:
    external:
      name: factory_dashboard_network
