name: Back-end

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Chekout code
      uses: actions/checkout@v2

      
    - name: Login to Github registry ghcr
      uses: docker/login-action@v1
      with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.TOKEN_FACTORY_DASHBOARD }}
         
    - name: Create env file
      run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
         
    - name: Build image and push Dockerfile
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        context: .
        push: true
        tags: ghcr.io/pungpeee/factory-dashboard:main
   
    - name: Publish compose file
      uses: appleboy/ssh-action@v0.1.8
      with: 
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         source: .
         target: .
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      
      - name: Deploy execute command ssh to remote server
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         script: |
           docker-compose down -f Factory-Dashboard/docker-compose.yml
           docker pull ghcr.io/pungpeee/factory-dashboard:main
           docker-compose up -f Factory-Dashboard/docker-compose.yml -d
           docker ps -a
